### ISSUE TITLE
Question: Dovecot/IMAP user creation

### ISSUE THREAD

**Issue by jordanbrock** [sovereign/sovereign#18]
I am setting up a server with the following config:

```
mail_server_hostname: example.com
mail_mysql_username: mailuser
mail_mysql_password: password
mail_mysql_database: mailserver
mail_virtual_domains:
  - name: example.com
    pk_id: 1
    primary_user: bill
mail_virtual_users:
  - address: bill@example.com
    password_hash: HASH
    domain_pk_id: 1
  - address: steve@example.com
    password_hash: HASH
    domain_pk_id: 1
```

When I run ansible, the users are added to the mysql database(virtual_users) correctly, but only the "primary" user has a directory created under /decrypted-mail/example.com/

eg /decrypted-mail/example.com/bill

When I try and login using steve@example.com the following appears in /var/log/mail.log

```
mail.warn:Sep  3 08:32:30 (none) dovecot: imap(steve@example.com): Error: user steve@example.com: Initialization failed: Namespace '': mkdir(/decrypted-mail/example.com/steve) failed: Permission denied (euid=5000(vmail) egid=5000(vmail) missing +w perm: /decrypted-mail/example.com, dir owned by 0:0 mode=0755)
mail.warn:Sep  3 08:32:30 (none) dovecot: imap(steve@example.com): Error: Invalid user settings. Refer to server log for more information.
```

Should that directory be created by ansible during setup? Or should it be created by dovecot when the user first logs in? If the latter, then do we need to modify the permissions so it can create the directory?

Cheers,

Jordan
