### ISSUE TITLE
error at "import sql postfix"

### ISSUE THREAD

**Issue by moranon** [sovereign/sovereign#459]
started with a fresh digitalocean debian 7 x64 1gb server.
all tasks go well until  [mailserver | import sql postfix].

```
NOTIFIED: [mailserver | import sql postfix] ***********************************
failed: [1.2.3.4] => {"changed": true, "cmd": "PGPASSWORD='********' psql -h localhost -d mailserver -U mailuser -f /etc/postfix/import.sql --set ON_ERROR_STOP=1", "delta": "0:00:00.133241", "end": "2016-01-03 00:36:09.317482", "rc": 3, "start": "2016-01-03 00:36:09.184241", "warnings": []}
stderr: psql:/etc/postfix/import.sql:11: NOTICE:  CREATE TABLE will create implicit sequence "virtual_domains_id_seq" for serial column "virtual_domains.id"
psql:/etc/postfix/import.sql:11: NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "virtual_domains_pkey" for table "virtual_domains"
psql:/etc/postfix/import.sql:22: NOTICE:  CREATE TABLE will create implicit sequence "virtual_users_id_seq" for serial column "virtual_users.id"
psql:/etc/postfix/import.sql:22: NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "virtual_users_pkey" for table "virtual_users"
psql:/etc/postfix/import.sql:22: NOTICE:  CREATE TABLE / UNIQUE will create implicit index "virtual_users_email_key" for table "virtual_users"
psql:/etc/postfix/import.sql:34: NOTICE:  CREATE TABLE will create implicit sequence "virtual_aliases_id_seq" for serial column "virtual_aliases.id"
psql:/etc/postfix/import.sql:34: NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "virtual_aliases_pkey" for table "virtual_aliases"
psql:/etc/postfix/import.sql:52: ERROR:  insert or update on table "virtual_users" violates foreign key constraint "virtual_users_domain_id_fkey"
DETAIL:  Key (domain_id)=(2) is not present in table "virtual_domains".
stdout: DROP TABLE
DROP TABLE
DROP TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE INDEX
INSERT 0 1
INSERT 0 1

FATAL: all hosts have already failed -- aborting

TASK: [vpn | Copy dnsmasq configuration file into place] **********************
FATAL: no hosts matched or all hosts have already failed -- aborting
```

just can't figure out where the problem lies ... even tried without virtual_aliases at all but i'm getting the same error.

relevant part of user.yml:
```
# common
domain: test.com
main_user_name: admin
encfs_password: *****    # NOTE: must not contain dollar sign characters '$'

# database
db_admin_username: postgres
db_admin_password: *****

# mailserver
mail_db_password: "*****"
mail_db_opendmarc_password: *****
mail_virtual_domains:
  - name: "{{ domain }}"
    pk_id: 1
#  - name: TODO.com
#    pk_id: 2
mail_virtual_users:
  - account: "{{ main_user_name }}"
    domain: "{{ domain }}"
    password_hash: "*****"
    domain_pk_id: 1
  - account: "*****"
    domain: "{{ domain }}"
    password_hash: "*****"
    domain_pk_id: 2
  - account: "******"
    domain: "{{ domain }}"
    password_hash: "*****"
    domain_pk_id: 3
  - account: "*****"
    domain: "{{ domain }}"
    password_hash: "*****"
    domain_pk_id: 4
mail_virtual_aliases:
  - source: "root@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
  - source: "postmaster@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
  - source: "webmaster@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
mail_header_privacy: 1

```

really hoping you're able to help...
thank you very much!
