### ISSUE TITLE
Private key needed at the top of file referenced by SSLCertFile in znc configuration

### ISSUE THREAD

**Issue by hectcastro** [sovereign/sovereign#65]
In the SSL task under common roles, the following lines generate a combined certificate that is referenced in the template znc configuration file:

``` yml
- name: Create a combined version of the public cert with intermediate and root CAs
  shell: cat /etc/ssl/certs/wildcard_public_cert.crt /etc/ssl/certs/wildcard_ca.pem >
    /etc/ssl/certs/wildcard_combined.pem creates=/etc/ssl/certs/wildcard_combined.pem
```

The [znc documentation for setting up SSL](http://wiki.znc.in/Signed_SSL_certificate) suggests that `SSLCertFile` needs to reference a file that leads with a private key, followed by your certificate and the certificate bundle.

I had to execute the following to get znc to play nice with my Comodo wildcard certificate:

``` bash
$ sudo cat /etc/ssl/private/wildcard_private.key /etc/ssl/certs/wildcard_combined.pem > /tmp/znc.pem
$ sudo mv /tmp/znc.pem /var/lib/znc
$ sudo chown znc:znc /var/lib/znc/znc.pem
```

From here I altered `SSLCertFile` to point to `/var/lib/znc/znc.pem` instead of `/etc/ssl/certs/wildcard_combined.pem`.

Anyone else hit anything similar? Is this worth a pull request against the znc tasks?
